ALTER TABLE courses 
ADD COLUMN IF NOT EXISTS institution TEXT,
ADD COLUMN IF NOT EXISTS year TEXT,
ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'Rascunho',
ADD COLUMN IF NOT EXISTS disciplines_json JSONB DEFAULT '[]'::jsonb;
