INSERT INTO public.courses (id, title, subtitle, hours, lessons, disciplines_count) VALUES ('cho-cbmmg-2027', 'CURSO OFICIAL PREMIUM - CHO CBMMG 2027', 'Curso de Habilitação de Oficiais Bombeiros Militares. Prepare-se com rigor militar e suporte tecnológico de ponta.', 480, 120, 14) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.course_modules (id, course_id, title, description, lessons_count, pdfs_count, questions_count) VALUES ('mod-01', 'cho-cbmmg-2027', 'Módulo 01: Direito Constitucional', 'Fundamentos da constituição, direitos e garantias fundamentais e a segurança pública na CF/88.', 12, 8, 45) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.course_modules (id, course_id, title, description, lessons_count, pdfs_count, questions_count) VALUES ('mod-02', 'cho-cbmmg-2027', 'Módulo 02: Direito Administrativo', 'Atos administrativos, poderes da administração, agentes públicos e responsabilidade civil do Estado.', 15, 10, 60) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.course_modules (id, course_id, title, description, lessons_count, pdfs_count, questions_count) VALUES ('mod-03', 'cho-cbmmg-2027', 'Módulo 03: Direito Penal Militar', 'Crimes militares em tempo de paz e em tempo de guerra, aplicação da lei penal militar e penas.', 20, 12, 80) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.course_modules (id, course_id, title, description, lessons_count, pdfs_count, questions_count) VALUES ('mod-04', 'cho-cbmmg-2027', 'Módulo 04: Regulamento Disciplinar', 'CEDM (Código de Ética e Disciplina dos Militares de MG), transgressões disciplinares e rito do PAD.', 10, 5, 30) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.courses (id, title, subtitle, hours, lessons, disciplines_count) VALUES ('cfo-cbmmg-2027', 'CURSO PREPARATÓRIO ELITE - CFO CBMMG 2027', 'Curso de Formação de Oficiais. Prepare-se para a liderança e comando com conteúdo profundo e simulados de alto rendimento.', 600, 180, 18) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.course_modules (id, course_id, title, description, lessons_count, pdfs_count, questions_count) VALUES ('mod-cfo-01', 'cfo-cbmmg-2027', 'Módulo 01: Física e Química do Fogo', 'Dinâmica de incêndios, propagação de calor e propriedades químicas dos materiais combustíveis.', 25, 15, 90) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.course_modules (id, course_id, title, description, lessons_count, pdfs_count, questions_count) VALUES ('mod-cfo-02', 'cfo-cbmmg-2027', 'Módulo 02: Tática de Combate a Incêndio', 'Estratégias de extinção de chamas, resgate em estruturas colapsadas e salvamento veicular.', 30, 20, 110) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.courses (id, title, subtitle, hours, lessons, disciplines_count) VALUES ('eap-cbmmg-2026', 'EXAME DE APTIDÃO PROFISSIONAL - EAP CBMMG 2026', 'Revisão focada e intensiva para promoção de praças e oficiais, abordando atualizações doutrinárias e regulamentos vigentes.', 150, 40, 6) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.course_modules (id, course_id, title, description, lessons_count, pdfs_count, questions_count) VALUES ('mod-eap-01', 'eap-cbmmg-2026', 'Módulo 01: Legislação Institucional Aplicada', 'Regulamento de promoção de praças, estatuto militar e prerrogativas da carreira de segurança.', 12, 6, 40) ON CONFLICT (id) DO NOTHING;

INSERT INTO public.questions (id, banca, year, discipline, subject, text, alternatives, correct, explanation) VALUES ('Q-28491', 'CRS/PMMG', 2023, 'Direito Constitucional', 'Forças Armadas e Segurança Pública', 'No que tange aos direitos, deveres e regramento constitucional dos militares dos Estados, Distrito Federal e Territórios, bem como à organização das Forças Armadas, assinale a alternativa CORRETA em conformidade com a Constituição Federal de 1988:', '[{"letter":"A","text":"As Forças Armadas são constituídas pela Marinha, pelo Exército, pela Aeronáutica e pelas Forças Auxiliares, sendo estas últimas organizadas sob comando da união em tempo de paz."},{"letter":"B","text":"Ao militar são proibidas a sindicalização e a greve, sendo-lhe, contudo, permitido o alistamento eleitoral e a filiação a partidos políticos enquanto estiver em serviço ativo."},{"letter":"C","text":"O militar em serviço ativo que aceitar cargo público civil permanente será transferido para a reserva, nos termos da lei, mantendo o direito à promoção por antiguidade."},{"letter":"D","text":"O oficial da Polícia Militar só perderá o posto e a patente se for julgado indigno do oficialato ou com ele incompatível, por decisão de tribunal militar de caráter permanente ou de tribunal de justiça comum."}]'::jsonb, 'D', 'O Art. 142, § 3º, VI da CF/88, aplicável aos militares dos Estados por força do Art. 42, § 1º, estabelece que o oficial só perderá o posto e a patente se for julgado indigno do oficialato ou com ele incompatível, por decisão de tribunal militar de caráter permanente em tempo de paz ou de tribunal especial em tempo de guerra. O Art. 42, § 2º dita que o tribunal militar estadual ou o Tribunal de Justiça apreciará a indignidade.') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.questions (id, banca, year, discipline, subject, text, alternatives, correct, explanation) VALUES ('Q-19042', 'CRS/PMMG', 2024, 'Regulamento Disciplinar', 'CEDM - Lei Estadual 14.310/02', 'O Código de Ética e Disciplina dos Militares de Minas Gerais (Lei Estadual nº 14.310/2002) regulamenta a conduta militar. Diante das disposições contidas na referida lei, assinale a opção que indica uma transgressão disciplinar classificada como GRAVE:', '[{"letter":"A","text":"Deixar de apresentar-se, logo que ciente, à autoridade competente quando convocado para depor ou prestar esclarecimentos em inquérito administrativo."},{"letter":"B","text":"Faltar ao serviço para o qual esteja nominalmente escalado ou abandonar o posto ou serviço para o qual tenha sido designado, sem justa causa."},{"letter":"C","text":"Apresentar-se para o serviço sem o fardamento regulamentar previsto para a atividade, ou com fardamento desalinhado ou incompleto."},{"letter":"D","text":"Deixar de prestar a devida continência militar a superior hierárquico ou de responder à continência de subordinado, por mera desatenção."}]'::jsonb, 'B', 'Faltar ou abandonar o posto/serviço sem justa causa é uma transgressão de natureza GRAVE (Art. 13 do CEDM). As demais alternativas tratam de transgressões médias ou leves, ou configuram condutas de menor potencial ofensivo disciplinar.') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.questions (id, banca, year, discipline, subject, text, alternatives, correct, explanation) VALUES ('Q-32405', 'CRS/PMMG', 2023, 'Direito Administrativo', 'Atos Administrativos', 'O ato administrativo consiste na declaração do Estado ou de quem o represente, que produz efeitos jurídicos imediatos. Dentre os elementos ou requisitos de validade do ato administrativo, assinale a alternativa que descreve CORRETAMENTE o elemento da ''Competência'':', '[{"letter":"A","text":"É o efeito jurídico imediato que o ato produz na ordem jurídica, devendo sempre ser lícito e moral."},{"letter":"B","text":"Consiste no poder outorgado por lei ao agente público para o desempenho de suas atribuições, sendo este um requisito intransferível e inderrogável por acordo das partes."},{"letter":"C","text":"Representa a motivação de fato e de direito que autorizou a expedição e o conteúdo do ato público administrativo."},{"letter":"D","text":"Trata-se do procedimento externo exigido por lei para a perfeita exteriorização da vontade do administrador."}]'::jsonb, 'B', 'A competência (ou sujeito) é o poder outorgado pela lei ao agente público para o exercício de suas funções. Apresenta como características a irrenunciabilidade, a intransferibilidade e a inderrogabilidade (salvo os casos legais de delegação e avocação).') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.questions (id, banca, year, discipline, subject, text, alternatives, correct, explanation) VALUES ('Q-45019', 'CRS/PMMG', 2022, 'Direito Penal Militar', 'Crimes Contra a Autoridade ou Disciplina', 'De acordo com o Código Penal Militar (Decreto-Lei nº 1.001/1969), o crime de Recusa de Obediência (Art. 163) configura crime de extrema gravidade para o serviço de caserna. Assinale a conduta típica que caracteriza esse crime:', '[{"letter":"A","text":"Deixar de cumprir ordem recebida de superior hierárquico sobre assunto de serviço ou dever imposto em lei, regulamento ou instrução."},{"letter":"B","text":"Recusar obediência a ordem do superior sobre assunto de serviço, ou de dever imposto por lei, regulamento ou instrução."},{"letter":"C","text":"Promover a reunião de militares ou nela tomar parte, para discutir ato de superior ou assunto disciplinar interno."},{"letter":"D","text":"Opor-se à execução de ato legal, mediante violência ou ameaça a superior ou sentinela."}]'::jsonb, 'B', 'O crime de Recusa de Obediência (Art. 163 do CPM) tem como núcleo ''recusar obediência a ordem do superior sobre assunto de serviço, ou de dever imposto sob preceito de lei, regulamento ou instrução''. Deixar de cumprir ordem (sem recusa expressa) tipifica o crime de Deserção de Dever ou Prevaricação/Descumprimento de Serviço do Art. 196 ou outro tipo penal específico.') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.questions (id, banca, year, discipline, subject, text, alternatives, correct, explanation) VALUES ('Q-11482', 'CRS/PMMG', 2024, 'Direito Constitucional', 'Remédios Constitucionais', 'Os remédios constitucionais são garantias fundamentais destinadas a assegurar o exercício de direitos individuais violados por atos de autoridade. No contexto das atividades policiais e do controle de legalidade, assinale a afirmativa CORRETA referente ao Mandado de Segurança Coletivo:', '[{"letter":"A","text":"Pode ser impetrado por qualquer cidadão em pleno gozo de seus direitos políticos, visando anular ato lesivo ao patrimônio público."},{"letter":"B","text":"Pode ser impetrado por partido político com representação no Congresso Nacional, ou por organização sindical, entidade de classe ou associação legalmente constituída e em funcionamento há pelo menos um ano, em defesa dos interesses de seus membros ou associados."},{"letter":"C","text":"Consiste na ação judicial cabível sempre que a falta de norma regulamentadora torne inviável o exercício dos direitos e liberdades constitucionais."},{"letter":"D","text":"É o remédio cabível para assegurar o conhecimento de informações relativas à pessoa do impetrante, constantes de registros ou bancos de dados governamentais."}]'::jsonb, 'B', 'O Art. 5º, LXX da CF/88 estabelece que o mandado de segurança coletivo pode ser impetrado por: a) partido político com representação no Congresso Nacional; b) organização sindical, entidade de classe ou associação legalmente constituída e em funcionamento há pelo menos um ano, em defesa dos interesses de seus membros ou associados.') ON CONFLICT (id) DO NOTHING;

INSERT INTO public.law_articles (id, title, category, citation, content, related_questions) VALUES ('lei-01', 'Artigo 142 da Constituição Federal (Das Forças Armadas)', 'Constituição da República Federativa do Brasil de 1988', 'Art. 142, CF/88', 'As Forças Armadas, constituídas pela Marinha, pelo Exército e pela Aeronáutica, são instituições nacionais permanentes e regulares, organizadas com base na hierarquia e na disciplina, sob a autoridade suprema do Presidente da República, e destinam-se à defesa da Pátria, à garantia dos poderes constitucionais e, por iniciativa de qualquer destes, da lei e da ordem.

§ 1º Lei complementar estabelecerá as normas gerais a serem adotadas na organização, no preparo e no emprego das Forças Armadas.

§ 2º Não caberá habeas corpus em relação a punições disciplinares militares.', '["Q-28491"]'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.law_articles (id, title, category, citation, content, related_questions) VALUES ('lei-02', 'Artigo 144 da Constituição Federal (Da Segurança Pública)', 'Constituição da República Federativa do Brasil de 1988', 'Art. 144, CF/88', 'A segurança pública, dever do Estado, direito e responsabilidade de todos, é exercida para a preservação da ordem pública e da incolumidade das pessoas e do patrimônio, através dos seguintes órgãos:
I - polícia federal;
II - polícia rodoviária federal;
III - polícia ferroviária federal;
IV - polícias civis;
V - polícias militares e corpos de bombeiros militares.

§ 5º Às polícias militares cabem a polícia ostensiva e a preservação da ordem pública; aos corpos de bombeiros militares, além das atribuições definidas em lei, incumbe a execução de atividades de defesa civil.', '["Q-28491","Q-11482"]'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.law_articles (id, title, category, citation, content, related_questions) VALUES ('lei-03', 'Artigo 13 do CEDM (Classificação das Transgressões)', 'Regulamento Disciplinar', 'Art. 13, Lei Estadual 14.310/02', 'As transgressões disciplinares são classificadas em graves, médias e leves, conforme sua gravidade e repercussão no serviço ou na imagem das Instituições Militares Estaduais.

São transgressões de natureza GRAVE:
- Faltar ao serviço para o qual esteja nominalmente escalado ou abandonar o posto ou serviço sem justa causa;
- Praticar ato de violência física ou moral contra superior, igual ou subordinado;
- Utilizar-se do cargo ou da função militar para obter proveito pessoal ou para terceiros, em descumprimento dos deveres éticos.', '["Q-19042"]'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.law_articles (id, title, category, citation, content, related_questions) VALUES ('lei-04', 'Artigo 163 do Código Penal Militar (Recusa de Obediência)', 'Penal Militar', 'Art. 163, Dec-Lei 1.001/69', 'Recusar obediência a ordem do superior sobre assunto de serviço, ou de dever imposto sob preceito de lei, regulamento ou instrução:

Pena - detenção, de um a dois anos, se o fato não constitui crime mais grave.

Este crime protege a autoridade e a disciplina na caserna, sendo classificado como crime de mera conduta, consumando-se no exato momento da recusa manifesta pelo militar subordinado diante de ordem legal e clara de superior.', '["Q-45019"]'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.law_articles (id, title, category, citation, content, related_questions) VALUES ('lei-05', 'Artigo 5º da Constituição Federal (Direitos e Deveres Individuais e Coletivos)', 'Constituição da República Federativa do Brasil de 1988', 'Art. 5º, CF/88', 'Todos são iguais perante a lei, sem distinção de qualquer natureza, garantindo-se aos brasileiros e aos estrangeiros residentes no País a inviolabilidade do direito à vida, à liberdade, à igualdade, à segurança e à propriedade, nos termos seguintes:

LXX - o mandado de segurança coletivo pode ser impetrado por:
a) partido político com representação no Congresso Nacional;
b) organização sindical, entidade de classe ou associação legalmente constituída e em funcionamento há pelo menos um ano, em defesa dos interesses de seus membros ou associados.', '["Q-11482"]'::jsonb) ON CONFLICT (id) DO NOTHING;

INSERT INTO public.badges (id, title, description, icon) VALUES ('badge-1', 'Grito de Guerra', 'Alistou-se na caserna do Cabo Véio.', 'ShieldAlert') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.badges (id, title, description, icon) VALUES ('badge-2', 'Sob Pressão', 'Resolveu 100 questões com aproveitamento superior a 80%.', 'Flame') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.badges (id, title, description, icon) VALUES ('badge-3', 'Inabalável', 'Manteve 10 dias seguidos de estudos ativos na plataforma.', 'CalendarCheck') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.badges (id, title, description, icon) VALUES ('badge-4', 'Selo de Honra (Top 1%)', 'Atingiu nota média de 9.2 em três simulados seguidos de nível oficial.', 'Award') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.badges (id, title, description, icon) VALUES ('badge-5', 'Especialista em CFD/CEDM', 'Gabaritou um micro-simulado focado do Tutor IA sobre Ética Militar.', 'Compass') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.badges (id, title, description, icon) VALUES ('badge-6', 'General do Tópico', 'Pesquisou e resolveu todas as questões correlatas de 5 Leis Inteligentes.', 'Crown') ON CONFLICT (id) DO NOTHING;

INSERT INTO public.mock_simulators (id, title, description, questions_count, duration, status) VALUES ('sim-01', 'CHO CBMMG Simulado Geral 01', 'Foco em Legislação Institucional, Direito Penal Militar e Atividades de Defesa Civil.', 50, '02h 00m', 'aberto') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.mock_simulators (id, title, description, questions_count, duration, status) VALUES ('sim-02', 'CFO CBMMG Simulado Especial 04', 'Simulado geral abrangendo todas as matérias e exigências regulamentares do CBMMG.', 40, '01h 40m', 'finalizado') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.mock_simulators (id, title, description, questions_count, duration, status) VALUES ('sim-03', 'Simulado Adaptativo de Reforço (TUTOR IA)', 'Gerado dinamicamente com base em suas fraquezas recentes de Direito Administrativo e Constitucional do Bombeiro Militar.', 5, '45m', 'recomendado') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.mock_simulators (id, title, description, questions_count, duration, status) VALUES ('sim-04', 'Simulado de Ranking Geral CBMMG (Oficiais)', 'Competição aberta para todos os candidatos bombeiros com ranking estadual ao vivo.', 50, '02h 30m', 'bloqueado') ON CONFLICT (id) DO NOTHING;
